version: "3.7"

services:
  php:
    container_name: hyperdrive-php
    working_dir: /application
    image: php:7.4.12-alpine
    logging:
        driver: none
    volumes:
      - .:/application

  composer:
    container_name: hyperdrive-composer
    working_dir: /application
    image: composer:2.0.7
    volumes:
      - .:/application
